# Generated by Django 5.0.4 on 2024-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='issued_date',
            field=models.DateField(auto_now=True),
        ),
    ]
