# Generated by Django 5.0.4 on 2024-05-13 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0003_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_quantity', models.PositiveIntegerField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p_app.purchaseorder')),
            ],
        ),
    ]
