# Generated by Django 5.0.4 on 2024-05-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0004_alter_invoice_payment_due_date_goodsreceivednotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednotice',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
