# Generated by Django 5.0.4 on 2024-05-15 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0005_goodsreceivednotice_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p2p_app.supplier'),
        ),
    ]
