# Generated by Django 5.0.4 on 2024-05-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0008_requisition_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
    ]
