# Generated by Django 5.0.4 on 2024-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0012_product_requisition_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_tax',
        ),
        migrations.AddField(
            model_name='requisition',
            name='customer_tax',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='requisition',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisition',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
