# Generated by Django 5.0.4 on 2024-06-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0015_supplier_user_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
