# Generated by Django 5.0.4 on 2024-06-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p_app', '0016_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_due_date',
        ),
    ]
