from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('supplier_dashboard/', views.supplier_dashboard_view, name='supplier_dashboard'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/add/', views.add_supplier, name='add_supplier'),
    path('suppliers/<int:pk>/', views.supplier_detail, name='supplier_detail'),
    path('suppliers/<int:pk>/edit/', views.edit_supplier, name='edit_supplier'),
    path('suppliers/<int:pk>/delete/', views.delete_supplier, name='delete_supplier'),
    path('purchase_orders/', views.purchase_order_list, name='purchase_order_list'),
    path('purchase_orders/add/', views.add_purchase_order, name='add_purchase_order'),
    path('purchase_orders/<int:pk>/', views.purchase_order_detail, name='purchase_order_detail'),
    path('purchase_orders/<int:pk>/edit/', views.edit_purchase_order, name='edit_purchase_order'),
    path('purchase_orders/<int:pk>/delete/', views.delete_purchase_order, name='delete_purchase_order'),
    path('requisitions/', views.requisition_list, name='requisition_list'),
    path('requisitions/add/', views.add_requisition, name='add_requisition'),
    path('requisitions/<int:pk>/', views.requisition_detail, name='requisition_detail'),
    path('requisitions/<int:pk>/edit/', views.edit_requisition, name='edit_requisition'),
    path('requisitions/<int:pk>/delete/', views.delete_requisition, name='delete_requisition'),
    path('invoices/', views.invoice_list, name='invoice_list'),
    path('invoices/add/', views.add_invoice, name='add_invoice'),
    path('invoices/<int:pk>/', views.invoice_detail, name='invoice_detail'),
    path('invoices/<int:pk>/edit/', views.edit_invoice, name='edit_invoice'),
    path('invoices/<int:pk>/delete/', views.delete_invoice, name='delete_invoice'),
    path('requisition/<int:requisition_id>/pdf/', views.generate_requisition_pdf, name='generate_requisition_pdf'),
    path('purchase_order/<int:purchase_order_id>/pdf/', views.generate_purchase_pdf, name='generate_purchase_pdf'),
    path('invoice/<int:invoice_id>/pdf/', views.generate_invoice_pdf, name='generate_invoice_pdf'),
    path('purchase_orders/<int:purchase_order_id>/create_grn/', views.create_grn, name='create_grn'),
    path('grn_list/', views.grn_list, name='grn_list'),
    path('grn/<int:grn_id>/', views.grn_detail, name='grn_detail'),
    path('restricted', views.restricted_view, name='restricted_view'),
    path('reports/purchase_order_summary/', views.purchase_order_summary, name='purchase_order_summary'),
    path('reports/invoice_summary/', views.invoice_summary, name='invoice_summary'),
    path('reports/requisition_summary/', views.requisition_summary, name='requisition_summary'),
    # path('admin_dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('admin_dashboard/', views.pending_requisitions, name='pending_requisitions'),

]
handler403 = views.custom_permission_denied_view